{
    'name': 'Commprog plus',
    'version': 'Version',
    'summary': 'Summery',
    'description': 'Plus',
    'category': 'commprog',
    'author': 'Author',
    'website': 'web',
    'license': '',
    'depends': ['commprog'],
    'data': ['views/product_view.xml'],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
